version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: notes_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: notes_backend
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongo:27017"
      MONGO_DB_NAME: "notes_app"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_MINUTES: "120"
      CORS_ORIGINS: "http://localhost:3000"
    ports:
      - "8000:8000"
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]

  frontend:
    build: ./frontend
    container_name: notes_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:8000"
    ports:
      - "3000:3000"

volumes:
  mongo_data: